// The app's interactive "accent" (buttons, selected states, calendar today/selected-date,
// active nav, drag highlights, ...) is implemented as Tailwind's orange-* scale, whose actual
// hex values live as CSS custom properties (--color-orange-*) generated by Tailwind v4's
// @theme block in index.css. Overriding those custom properties at runtime — via an inline
// style on the document root, which always wins the cascade — reskins every orange-* utility
// class across the whole app with zero per-component changes.

export interface AccentOption {
  id: string;
  label: string;
  swatch: string;
}

export const ACCENT_OPTIONS: AccentOption[] = [
  { id: 'orange', label: '오렌지', swatch: '#FF9F0A' },
  { id: 'green', label: '그린', swatch: '#34C759' },
  { id: 'blue', label: '블루', swatch: '#0071E3' },
  { id: 'red', label: '레드', swatch: '#FF3B30' },
  { id: 'purple', label: '퍼플', swatch: '#AF52DE' },
  { id: 'pink', label: '핑크', swatch: '#FF2D55' },
  { id: 'teal', label: '틸', swatch: '#30B0C7' },
];

const ACCENT_SCALES: Record<string, Record<string, string>> = {
  orange: { '50': '#FFF4E5', '100': '#FFE9CC', '200': '#FFDDAE', '300': '#FFC77A', '400': '#FFB454', '500': '#FF9F0A', '600': '#E0890A', '700': '#B5650A', '800': '#8A4D08' },
  green:  { '50': '#E9F9EE', '100': '#D1F2DA', '200': '#A8E6BA', '300': '#7DD99C', '400': '#55CC81', '500': '#34C759', '600': '#248A3D', '700': '#1B6B2F', '800': '#124D21' },
  blue:   { '50': '#E8F2FE', '100': '#D1E5FD', '200': '#A3CBFB', '300': '#75B1F9', '400': '#409CFF', '500': '#0071E3', '600': '#0060C0', '700': '#004A94', '800': '#003569' },
  red:    { '50': '#FFEBEA', '100': '#FFD6D3', '200': '#FFB3AD', '300': '#FF8F86', '400': '#FF6961', '500': '#FF3B30', '600': '#D70015', '700': '#A80010', '800': '#7A000B' },
  purple: { '50': '#F6ECFB', '100': '#EBD6F6', '200': '#D9AEEE', '300': '#C687E5', '400': '#BC6EE0', '500': '#AF52DE', '600': '#9333C7', '700': '#7429A0', '800': '#571F78' },
  pink:   { '50': '#FFEAEF', '100': '#FFD1DC', '200': '#FFA3B8', '300': '#FF7595', '400': '#FF4E77', '500': '#FF2D55', '600': '#E01245', '700': '#B30D38', '800': '#85092A' },
  teal:   { '50': '#E6F6F9', '100': '#C7EBF1', '200': '#90D6E3', '300': '#58C1D5', '400': '#3EB6CC', '500': '#30B0C7', '600': '#2593A7', '700': '#1C7482', '800': '#13535D' },
};

const STORAGE_KEY = 'accentColor';

export function applyAccentTheme(color: string | null | undefined): void {
  const scale = ACCENT_SCALES[color ?? 'orange'] ?? ACCENT_SCALES.orange;
  const root = document.documentElement;
  Object.entries(scale).forEach(([shade, hex]) => {
    root.style.setProperty(`--color-orange-${shade}`, hex);
  });
}

export function applyCachedAccentTheme(): void {
  applyAccentTheme(localStorage.getItem(STORAGE_KEY));
}

export function cacheAccentTheme(color: string | null | undefined): void {
  if (color) localStorage.setItem(STORAGE_KEY, color);
  else localStorage.removeItem(STORAGE_KEY);
}
